export const ITINERARY_DAYS = [
  {
    id: 'd1',
    date: '10月4日',
    weekday: '周日',
    city: '京都',
    title: '抵达京都 · 花火备选',
    eyebrow: '香港 → 大阪 → 京都',
    summary: 'HB340 抵达关西机场，傍晚入住河原町；花火仅在提前购票且未延误时前往。',
    status: { tone: 'warning', label: '花火：备选・未购票' },
    map: { center: [34.9305, 135.691], zoom: 9 },
    route: ['hb340', 'kix-arrival', 'kyoto-station', 'kyoto-hotel', 'joyo-fireworks'],
    stops: [
      {
        id: 'hb340',
        time: '08:20–13:05',
        name: '大湾区航空 HB340',
        type: 'flight',
        summary: '香港国际机场 → 大阪关西国际机场',
        detail: '抵达后预留入境、取行李和换乘时间；航班时刻以航空公司通知为准。',
      },
      {
        id: 'kix-arrival',
        time: '13:05–14:30',
        name: '关西国际机场',
        type: 'airport',
        summary: '入境、取行李，前往 JR 车站',
        detail: '乘 JR HARUKA 前往京都站，现场以实际班次为准。',
        coordinates: [34.43472, 135.24401],
        officialUrl: 'https://www.kansai-airport.or.jp/en/',
      },
      {
        id: 'kyoto-station',
        time: '约15:40',
        name: '京都站',
        type: 'transit',
        summary: '八条口换乘前往四条河原町',
        detail: '可按现场情况选择 HOOP 巴士或其他公共交通前往酒店。',
        coordinates: [34.985849, 135.758767],
        officialUrl: 'https://www.westjr.co.jp/global/en/',
      },
      {
        id: 'kyoto-hotel',
        time: '16:00–17:00',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '办理入住，放下行李',
        detail: '位于河原町通四条附近，步行可到祇园四条站。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
      {
        id: 'joyo-fireworks',
        time: '19:00–19:40',
        name: '城阳秋花火 2026',
        type: 'event',
        summary: '备选・未购票｜京都府立木津川运动公园',
        detail: '仅在提前买到预售票、天气允许且17:00左右能离开酒店时前往；现场不售票。否则留在河原町／祇园休息和用餐。',
        coordinates: [34.84457, 135.77851],
        status: { tone: 'warning', label: '备选・未购票' },
        officialUrl: 'https://www.city.joyo.kyoto.jp/joint/0000012600.html',
        optional: true,
        weatherSensitive: true,
      },
    ],
  },
  {
    id: 'd2',
    date: '10月5日',
    weekday: '周一',
    city: '京都',
    title: '岚山和服 · 山寺竹林环线',
    eyebrow: '河原町 → 嵯峨岚山 → 阪急岚山 → 河原町',
    summary: '从京都酒店出发，在 MOCOMOCO 完成和服妆造；按北高南低的方向走完山寺、竹林、天龙寺与渡月桥，17:30前归还。',
    status: { tone: 'warning', label: 'MOCOMOCO待预约・17:30前归还' },
    map: { center: [35.0148, 135.6748], zoom: 14 },
    route: [
      'kyoto-hotel-d2-start',
      'saga-arashiyama-station',
      'mocomoco-fitting',
      'jojakkoji',
      'mikami-shrine',
      'bamboo-grove-north',
      'nonomiya-shrine',
      'tenryuji',
      'arashiyama-shopping-street',
      'togetsukyo',
      'mocomoco-return',
      'hankyu-arashiyama',
      'kyoto-hotel-d2-return',
    ],
    stops: [
      {
        id: 'kyoto-hotel-d2-start',
        time: '08:15',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '从京都酒店出发前往嵯峨岚山',
        detail: '先前往京都站，再乘 JR 嵯峨野线到嵯峨岚山站；当天按实际班次调整。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
      {
        id: 'saga-arashiyama-station',
        time: '约09:00',
        name: '嵯峨岚山 JR／小火车站',
        type: 'transit',
        summary: '出站后步行4分钟到 MOCOMOCO',
        detail: 'JR嵯峨岚山站与小火车嵯峨站相邻；认准南口方向前往和服店。',
        coordinates: [35.0187493, 135.6811814],
        officialUrl: 'https://www.jr-odekake.net/eki/top?id=0610704',
      },
      {
        id: 'mocomoco-fitting',
        time: '09:05–10:15',
        name: 'MOCOMOCO 岚山本店',
        type: 'activity',
        summary: '和服挑选、着装与妆造',
        detail: '地址：616-8384 京都市右京区嵯峨天龍寺造路町6-2。最迟归还时间以预约确认为准，当前按17:30前规划。',
        coordinates: [35.01535, 135.67802],
        status: { tone: 'warning', label: '待预约' },
        officialUrl: 'https://mocomoco-kimono.com/arashiyama/',
      },
      {
        id: 'jojakkoji',
        time: '约10:30',
        name: '常寂光寺',
        type: 'sight',
        summary: 'MOCOMOCO → 步行15分钟・上坡',
        detail: '这是当天唯一明显上坡段，先完成北侧山上的景点，后续路线以下坡和平路为主。',
        coordinates: [35.0197, 135.6686],
        officialUrl: 'https://www.jojakko-ji.or.jp/',
      },
      {
        id: 'mikami-shrine',
        time: '约11:20',
        name: '御髪神社',
        type: 'sight',
        summary: '常寂光寺 → 步行6分钟・下坡',
        detail: '从常寂光寺下坡前往小仓池畔的御髪神社。',
        coordinates: [35.0176, 135.6697],
      },
      {
        id: 'bamboo-grove-north',
        time: '约11:35',
        name: '竹林小径（北口）',
        type: 'walk',
        summary: '御髪神社 → 步行7分钟',
        detail: '由北口进入竹林，沿小径向南穿行，避免折返。',
        coordinates: [35.0186, 135.6708],
        officialUrl: 'https://kyoto.travel/en/other_attractions/268.html',
      },
      {
        id: 'nonomiya-shrine',
        time: '约12:00',
        name: '野宫神社',
        type: 'sight',
        summary: '竹林小径南口 → 步行8分钟',
        detail: '从竹林南端顺路前往野宫神社。',
        coordinates: [35.0178429, 135.6744755],
      },
      {
        id: 'tenryuji',
        time: '约12:20',
        name: '天龙寺',
        type: 'sight',
        summary: '野宫神社 → 步行10分钟',
        detail: '按当天排队和体力决定寺院及庭园停留时间。',
        coordinates: [35.0157, 135.6737],
        officialUrl: 'https://www.tenryuji.com/en/',
      },
      {
        id: 'arashiyama-shopping-street',
        time: '约13:10',
        name: '岚山商业街',
        type: 'food',
        summary: '天龙寺正门 → 步行5分钟・午餐区域',
        detail: '在商业街安排午餐、甜品和短暂休息，控制排队时间。',
        coordinates: [35.01531, 135.67784],
      },
      {
        id: 'togetsukyo',
        time: '约14:45',
        name: '渡月桥',
        type: 'sight',
        summary: '岚山商业街 → 步行12分钟',
        detail: '在桂川河边散步拍照，预留返回和服店的时间。',
        coordinates: [35.01285, 135.67777],
        officialUrl: 'https://kyoto.travel/en/other_attractions/155.html',
      },
      {
        id: 'mocomoco-return',
        time: '最迟17:30前',
        name: 'MOCOMOCO 岚山本店',
        type: 'deadline',
        summary: '渡月桥 → 步行14分钟・归还和服',
        detail: '地址：616-8384 京都市右京区嵯峨天龍寺造路町6-2。建议不要压线抵达。',
        coordinates: [35.01535, 135.67802],
        status: { tone: 'warning', label: '17:30前归还' },
        officialUrl: 'https://mocomoco-kimono.com/arashiyama/',
      },
      {
        id: 'hankyu-arashiyama',
        time: '归还后',
        name: '阪急岚山站',
        type: 'transit',
        summary: 'MOCOMOCO → 步行7分钟',
        detail: '乘阪急岚山线，经桂站换乘京都本线回京都河原町。',
        coordinates: [35.0098527, 135.6823142],
        officialUrl: 'https://www.hankyu.co.jp/station/arashiyama.html',
      },
      {
        id: 'kyoto-hotel-d2-return',
        time: '傍晚',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '阪急电车返回河原町',
        detail: '回酒店休息，晚餐可在河原町或祇园一带弹性安排。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
    ],
  },
  {
    id: 'd3',
    date: '10月6日',
    weekday: '周二',
    city: '京都',
    title: '天授庵・南禅寺 · 哲学之道',
    eyebrow: '酒店 → 天授庵 → 银阁寺 → 八神社 → 酒店',
    summary: '从京都酒店出发，依次游览天授庵、南禅寺，再沿哲学之道由南向北走到银阁寺和八神社，最后返回酒店。',
    map: { center: [35.0193, 135.7961], zoom: 14 },
    route: [
      'kyoto-hotel-d3-start',
      'tenjuan',
      'nanzenji',
      'philosophers-path-south',
      'philosophers-path-north',
      'ginkakuji',
      'hachi-shrine',
      'kyoto-hotel-d3-return',
    ],
    stops: [
      {
        id: 'kyoto-hotel-d3-start',
        time: '08:15',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '从京都酒店出发前往天授庵',
        detail: '根据当天交通状况选择地铁、巴士或出租车前往南禅寺区域。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
      {
        id: 'tenjuan',
        time: '09:00',
        name: '天授庵',
        type: 'sight',
        summary: '庭园与南禅寺塔头',
        detail: '先游览天授庵，再步行衔接南禅寺主体区域。',
        coordinates: [35.0106297, 135.7922722],
        officialUrl: 'https://www.kyoto-kankou.or.jp/info_search/173',
      },
      {
        id: 'nanzenji',
        time: '10:00',
        name: '南禅寺',
        type: 'sight',
        summary: '山门、水路阁与寺院区域',
        detail: '天授庵参观后继续南禅寺，不再单列永观堂。',
        coordinates: [35.011259, 135.793218],
        officialUrl: 'https://www.nanzenji.or.jp/en/',
      },
      {
        id: 'philosophers-path-south',
        time: '约11:15',
        name: '哲学之道（南段）',
        type: 'walk',
        summary: '从南端沿疏水向北散步',
        detail: '从南禅寺区域衔接哲学之道南端，沿线安排午餐和咖啡。',
        coordinates: [35.0159, 135.7958],
        officialUrl: 'https://kyoto.travel/en/other_attractions/12.html',
      },
      {
        id: 'philosophers-path-north',
        time: '约13:15',
        name: '哲学之道（北段）',
        type: 'walk',
        summary: '继续向北走到银阁寺方向',
        detail: '沿疏水继续北行，抵达银阁寺前可短暂休息。',
        coordinates: [35.0258, 135.7956],
        officialUrl: 'https://kyoto.travel/en/other_attractions/12.html',
      },
      {
        id: 'ginkakuji',
        time: '约14:00',
        name: '银阁寺（慈照寺）',
        type: 'sight',
        summary: '哲学之道北端终点',
        detail: '留意最终入场时间，参观结束后前往附近的八神社。',
        coordinates: [35.02702, 135.7982],
        officialUrl: 'https://www.shokoku-ji.jp/en/ginkakuji/',
      },
      {
        id: 'hachi-shrine',
        time: '约15:30',
        name: '八神社',
        type: 'sight',
        summary: '银阁寺附近的小神社',
        detail: '地址：京都市左京区银阁寺町26。参拜后返回京都酒店。',
        coordinates: [35.027802, 135.796539],
      },
      {
        id: 'kyoto-hotel-d3-return',
        time: '约17:00',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '返回京都酒店',
        detail: '回河原町休息，晚餐在酒店周边弹性安排。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
    ],
  },
  {
    id: 'd4',
    date: '10月7日',
    weekday: '周三',
    city: '宇治 → 大阪',
    title: '宇治半日 · 转住大阪',
    eyebrow: '祇园四条 → 宇治 → 新世界',
    summary: '退房后把行李留在京都酒店，轻装游宇治，下午回酒店取行李再去大阪。',
    status: { tone: 'success', label: '核心游览约4–5小时' },
    map: { center: [34.795, 135.683], zoom: 10 },
    route: ['kyoto-hotel-checkout', 'byodoin', 'uji-omotesando', 'uji-river', 'ujigami', 'kyoto-hotel-pickup', 'osaka-hotel'],
    stops: [
      {
        id: 'kyoto-hotel-checkout',
        time: '08:30前',
        name: '京都酒店退房・寄存行李',
        type: 'hotel',
        summary: '轻装前往宇治',
        detail: '从祇园四条经中书岛换乘京阪宇治线。',
        coordinates: [35.00455, 135.76955],
      },
      {
        id: 'byodoin',
        time: '10:00',
        name: '平等院',
        type: 'sight',
        summary: '宇治核心景点',
        detail: '先完成核心参观，避免下午回程前时间不足。',
        coordinates: [34.88929, 135.80773],
        officialUrl: 'https://www.byodoin.or.jp/en/',
      },
      {
        id: 'uji-omotesando',
        time: '11:30',
        name: '平等院表参道',
        type: 'food',
        summary: '抹茶甜品与午餐',
        detail: '选择排队适中的店，不为单一家店压缩后续时间。',
        coordinates: [34.89104, 135.80755],
      },
      {
        id: 'uji-river',
        time: '12:30',
        name: '宇治川',
        type: 'walk',
        summary: '沿河散步与桥景',
        detail: '天气不佳时缩短河岸停留。',
        coordinates: [34.89368, 135.8086],
        weatherSensitive: true,
      },
      {
        id: 'ujigami',
        time: '13:15',
        name: '宇治上神社',
        type: 'sight',
        summary: '时间允许时前往',
        detail: '最晚14:30左右开始返程；时间不足可跳过。',
        coordinates: [34.89208, 135.81161],
        optional: true,
      },
      {
        id: 'kyoto-hotel-pickup',
        time: '约15:00',
        name: '返回京都酒店取行李',
        type: 'hotel',
        summary: '不要直接带大件行李游宇治',
        detail: '若酒店寄存政策变化，再考虑祇园四条或宇治站投币柜。',
        coordinates: [35.00455, 135.76955],
      },
      {
        id: 'osaka-hotel',
        time: '17:00–17:30',
        name: 'Grand Hostel LDK Osaka Shinsekai',
        type: 'hotel',
        summary: '入住大阪新世界酒店',
        detail: '祇园四条乘京阪至京桥，换大阪环状线到新今宫后步行。',
        coordinates: [34.65095, 135.5058],
      },
    ],
  },
  {
    id: 'd5',
    date: '10月8日',
    weekday: '周四',
    city: '大阪',
    title: '日本环球影城',
    eyebrow: '新今宫 → Universal City',
    summary: '全天 USJ，目标在官方公布开园前60–90分钟抵达。',
    status: { tone: 'warning', label: '出发前复核营业时间' },
    map: { center: [34.6584, 135.469], zoom: 12 },
    route: ['osaka-hotel-start', 'usj'],
    stops: [
      {
        id: 'osaka-hotel-start',
        time: '约06:45',
        name: '大阪酒店出发',
        type: 'hotel',
        summary: '新今宫 → 西九条 → Universal City',
        detail: '大阪环状线换 JR 梦咲线，预计约30分钟；按当天开园时间倒推。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'usj',
        time: '全天',
        name: '日本环球影城',
        type: 'theme-park',
        summary: '开园前60–90分钟抵达',
        detail: '若任天堂世界是重点，提前处理门票、区域入场与 Express Pass；园区可能早于标示时间放行。',
        coordinates: [34.66544, 135.43234],
        officialUrl: 'https://www.usj.co.jp/web/ja/jp/park-guide/schedule/park-hour/',
        ticketUrl: 'https://www.usj.co.jp/ticket/',
      },
    ],
  },
  {
    id: 'd6',
    date: '10月9日',
    weekday: '周五',
    city: '大阪 → 香港',
    title: '大阪美食随逛 · 回程',
    eyebrow: '新世界 → 难波 → 关西机场',
    summary: '白天以美食和随意逛街为主，16:30前回酒店取行李，乘 UO863 返回香港。',
    status: { tone: 'warning', label: '17:30前往机场' },
    map: { center: [34.6652, 135.496], zoom: 13 },
    route: ['osaka-hotel-checkout', 'shinsekai', 'kuromon', 'dotonbori', 'shinsaibashi', 'osaka-hotel-pickup', 'kix-departure'],
    stops: [
      {
        id: 'osaka-hotel-checkout',
        time: '上午',
        name: '退房・寄存行李',
        type: 'hotel',
        summary: '轻装逛大阪市区',
        detail: '先向酒店确认当日寄存和最晚领取时间。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'shinsekai',
        time: '09:30',
        name: '新世界・通天阁',
        type: 'food',
        summary: '早餐、街区散步',
        detail: '就在酒店周边，保持轻松节奏。',
        coordinates: [34.6525, 135.5063],
        officialUrl: 'https://www.tsutenkaku.co.jp/Guide-pdf/mishiran-guide-english.pdf',
      },
      {
        id: 'kuromon',
        time: '11:30',
        name: '黑门市场・日本桥',
        type: 'food',
        summary: '小吃与随意逛街',
        detail: '不安排必须购买的清单，按现场食欲和人流决定。',
        coordinates: [34.6653, 135.50604],
        officialUrl: 'https://kuromon.com/en/',
      },
      {
        id: 'dotonbori',
        time: '13:30',
        name: '道顿堀・难波',
        type: 'food',
        summary: '午餐、甜品与街区漫游',
        detail: '控制排队时间，给最后取行李和机场交通留缓冲。',
        coordinates: [34.66872, 135.50129],
      },
      {
        id: 'shinsaibashi',
        time: '14:45',
        name: '心斋桥',
        type: 'shopping',
        summary: '自由逛街',
        detail: '16:00左右开始返回酒店。',
        coordinates: [34.6748, 135.50142],
      },
      {
        id: 'osaka-hotel-pickup',
        time: '16:30前',
        name: '返回酒店取行李',
        type: 'deadline',
        summary: '最迟17:30前往机场',
        detail: '从新今宫或难波选择当天最顺的机场线路。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'kix-departure',
        time: '18:00–18:30',
        name: '关西国际机场',
        type: 'airport',
        summary: '香港快运 UO863｜21:30起飞',
        detail: '预留国际航班值机、退税、安检与登机时间；10月10日00:40抵达香港。',
        coordinates: [34.43472, 135.24401],
        officialUrl: 'https://www.hkexpress.com/en-hk/',
      },
    ],
  },
];
