export const ITINERARY_DAYS = [
  {
    id: 'd1',
    date: '10月4日',
    weekday: '周日',
    city: '京都',
    title: '抵达京都 · 花火备选',
    eyebrow: '香港 → 大阪 → 京都',
    summary: 'HB340 抵达关西机场，傍晚入住河原町；花火仅在提前购票且未延误时前往。',
    status: { tone: 'warning', label: '花火：备选・未购票' },
    map: { center: [34.9305, 135.691], zoom: 9 },
    route: ['hb340', 'kix-arrival', 'kyoto-station', 'kyoto-hotel', 'joyo-fireworks'],
    stops: [
      {
        id: 'hb340',
        time: '08:20–13:05',
        name: '大湾区航空 HB340',
        type: 'flight',
        summary: '香港国际机场 → 大阪关西国际机场',
        detail: '抵达后预留入境、取行李和换乘时间；航班时刻以航空公司通知为准。',
      },
      {
        id: 'kix-arrival',
        time: '13:05–14:30',
        name: '关西国际机场',
        type: 'airport',
        summary: '入境、取行李，前往 JR 车站',
        detail: '乘 JR HARUKA 前往京都站，现场以实际班次为准。',
        coordinates: [34.43472, 135.24401],
        officialUrl: 'https://www.kansai-airport.or.jp/en/',
      },
      {
        id: 'kyoto-station',
        time: '约15:40',
        name: '京都站',
        type: 'transit',
        summary: '八条口换乘前往四条河原町',
        detail: '可按现场情况选择 HOOP 巴士或其他公共交通前往酒店。',
        coordinates: [34.985849, 135.758767],
        officialUrl: 'https://www.westjr.co.jp/global/en/',
      },
      {
        id: 'kyoto-hotel',
        time: '16:00–17:00',
        name: 'GLANSIT 京都河原町',
        type: 'hotel',
        summary: '办理入住，放下行李',
        detail: '位于河原町通四条附近，步行可到祇园四条站。',
        coordinates: [35.00455, 135.76955],
        officialUrl: 'https://glansit.jp/en/kyotokawaramachi/',
      },
      {
        id: 'joyo-fireworks',
        time: '19:00–19:40',
        name: '城阳秋花火 2026',
        type: 'event',
        summary: '备选・未购票｜京都府立木津川运动公园',
        detail: '仅在提前买到预售票、天气允许且17:00左右能离开酒店时前往；现场不售票。否则留在河原町／祇园休息和用餐。',
        coordinates: [34.84457, 135.77851],
        status: { tone: 'warning', label: '备选・未购票' },
        officialUrl: 'https://www.city.joyo.kyoto.jp/joint/0000012600.html',
        optional: true,
        weatherSensitive: true,
      },
    ],
  },
  {
    id: 'd2',
    date: '10月5日',
    weekday: '周一',
    city: '京都',
    title: '和服妆造 · 岚山',
    eyebrow: '祇园 → 岚山 → 祇园',
    summary: '上午在酒店附近妆造，11:00出发去岚山；暂按18:00前归还和服。',
    status: { tone: 'neutral', label: '和服店待选' },
    map: { center: [35.0132, 135.714], zoom: 12 },
    route: ['kyoto-hotel-start', 'togetsukyo', 'tenryuji', 'bamboo-grove', 'saga-stroll', 'kyoto-hotel-return'],
    stops: [
      {
        id: 'kyoto-hotel-start',
        time: '09:00–10:45',
        name: '祇园附近和服妆造',
        type: 'activity',
        summary: '店铺待选，优先酒店步行范围',
        detail: '具体店名、地址与归还时间确认后再补地图坐标；目前不放置虚假标记。',
        status: { tone: 'neutral', label: '店铺待选' },
      },
      {
        id: 'togetsukyo',
        time: '12:00',
        name: '渡月桥',
        type: 'sight',
        summary: '岚山河岸与午餐',
        detail: '从京都河原町乘阪急，经桂换乘岚山线；穿和服时放慢步行速度。',
        coordinates: [35.01285, 135.67777],
        officialUrl: 'https://kyoto.travel/en/other_attractions/155.html',
      },
      {
        id: 'tenryuji',
        time: '13:15',
        name: '天龙寺',
        type: 'sight',
        summary: '庭园与寺院参观',
        detail: '是否入内按当天排队和体力决定。',
        coordinates: [35.0157, 135.6738],
        officialUrl: 'https://www.tenryuji.com/en/',
      },
      {
        id: 'bamboo-grove',
        time: '14:30',
        name: '竹林小径',
        type: 'walk',
        summary: '从天龙寺北门衔接竹林',
        detail: '热门时段拥挤，保持轻量拍照节奏。',
        coordinates: [35.01706, 135.67134],
      },
      {
        id: 'saga-stroll',
        time: '15:20',
        name: '嵯峨野街区',
        type: 'food',
        summary: '甜品、咖啡与随意散步',
        detail: '16:30–17:00之间开始返程，给和服归还留足余量。',
        coordinates: [35.01836, 135.68053],
      },
      {
        id: 'kyoto-hotel-return',
        time: '18:00前',
        name: '归还和服',
        type: 'deadline',
        summary: '暂定时间，选店后确认',
        detail: '若店铺要求更早归还，需要同步提前离开岚山。',
        status: { tone: 'warning', label: '暂定18:00前' },
      },
    ],
  },
  {
    id: 'd3',
    date: '10月6日',
    weekday: '周二',
    city: '京都',
    title: '东山北部 · 哲学之道',
    eyebrow: '南禅寺 → 银阁寺',
    summary: '沿东山北部由南向北慢走，午餐和咖啡留在哲学之道沿线。',
    map: { center: [35.0193, 135.7961], zoom: 14 },
    route: ['nanzenji', 'eikando', 'philosophers-path-south', 'honenin', 'ginkakuji'],
    stops: [
      {
        id: 'nanzenji',
        time: '09:00',
        name: '南禅寺・天授庵',
        type: 'sight',
        summary: '山门、水路阁与庭园',
        detail: '从南禅寺开始可避免哲学之道来回折返。',
        coordinates: [35.01142, 135.79446],
        officialUrl: 'https://www.nanzenji.or.jp/en/',
      },
      {
        id: 'eikando',
        time: '10:30',
        name: '永观堂',
        type: 'sight',
        summary: '寺院与庭园',
        detail: '若参观时间拉长，可压缩后续咖啡停留。',
        coordinates: [35.01466, 135.79521],
        officialUrl: 'https://www.eikando.or.jp/English/index_eng.html',
      },
      {
        id: 'philosophers-path-south',
        time: '11:30',
        name: '哲学之道（南段）',
        type: 'walk',
        summary: '沿疏水向北散步约2公里',
        detail: '沿线安排午餐、咖啡与小店停留。',
        coordinates: [35.01883, 135.79528],
        officialUrl: 'https://kyoto.travel/en/other_attractions/12.html',
      },
      {
        id: 'honenin',
        time: '14:00',
        name: '法然院',
        type: 'sight',
        summary: '安静的小寺院支线',
        detail: '体力不足时可直接沿主路前往银阁寺。',
        coordinates: [35.02245, 135.7982],
        optional: true,
      },
      {
        id: 'ginkakuji',
        time: '15:00',
        name: '银阁寺（慈照寺）',
        type: 'sight',
        summary: '哲学之道北端终点',
        detail: '留意最终入场时间，参观后返回河原町晚餐。',
        coordinates: [35.02702, 135.7982],
        officialUrl: 'https://www.shokoku-ji.jp/en/ginkakuji/',
      },
    ],
  },
  {
    id: 'd4',
    date: '10月7日',
    weekday: '周三',
    city: '宇治 → 大阪',
    title: '宇治半日 · 转住大阪',
    eyebrow: '祇园四条 → 宇治 → 新世界',
    summary: '退房后把行李留在京都酒店，轻装游宇治，下午回酒店取行李再去大阪。',
    status: { tone: 'success', label: '核心游览约4–5小时' },
    map: { center: [34.795, 135.683], zoom: 10 },
    route: ['kyoto-hotel-checkout', 'byodoin', 'uji-omotesando', 'uji-river', 'ujigami', 'kyoto-hotel-pickup', 'osaka-hotel'],
    stops: [
      {
        id: 'kyoto-hotel-checkout',
        time: '08:30前',
        name: '京都酒店退房・寄存行李',
        type: 'hotel',
        summary: '轻装前往宇治',
        detail: '从祇园四条经中书岛换乘京阪宇治线。',
        coordinates: [35.00455, 135.76955],
      },
      {
        id: 'byodoin',
        time: '10:00',
        name: '平等院',
        type: 'sight',
        summary: '宇治核心景点',
        detail: '先完成核心参观，避免下午回程前时间不足。',
        coordinates: [34.88929, 135.80773],
        officialUrl: 'https://www.byodoin.or.jp/en/',
      },
      {
        id: 'uji-omotesando',
        time: '11:30',
        name: '平等院表参道',
        type: 'food',
        summary: '抹茶甜品与午餐',
        detail: '选择排队适中的店，不为单一家店压缩后续时间。',
        coordinates: [34.89104, 135.80755],
      },
      {
        id: 'uji-river',
        time: '12:30',
        name: '宇治川',
        type: 'walk',
        summary: '沿河散步与桥景',
        detail: '天气不佳时缩短河岸停留。',
        coordinates: [34.89368, 135.8086],
        weatherSensitive: true,
      },
      {
        id: 'ujigami',
        time: '13:15',
        name: '宇治上神社',
        type: 'sight',
        summary: '时间允许时前往',
        detail: '最晚14:30左右开始返程；时间不足可跳过。',
        coordinates: [34.89208, 135.81161],
        optional: true,
      },
      {
        id: 'kyoto-hotel-pickup',
        time: '约15:00',
        name: '返回京都酒店取行李',
        type: 'hotel',
        summary: '不要直接带大件行李游宇治',
        detail: '若酒店寄存政策变化，再考虑祇园四条或宇治站投币柜。',
        coordinates: [35.00455, 135.76955],
      },
      {
        id: 'osaka-hotel',
        time: '17:00–17:30',
        name: 'Grand Hostel LDK Osaka Shinsekai',
        type: 'hotel',
        summary: '入住大阪新世界酒店',
        detail: '祇园四条乘京阪至京桥，换大阪环状线到新今宫后步行。',
        coordinates: [34.65095, 135.5058],
      },
    ],
  },
  {
    id: 'd5',
    date: '10月8日',
    weekday: '周四',
    city: '大阪',
    title: '日本环球影城',
    eyebrow: '新今宫 → Universal City',
    summary: '全天 USJ，目标在官方公布开园前60–90分钟抵达。',
    status: { tone: 'warning', label: '出发前复核营业时间' },
    map: { center: [34.6584, 135.469], zoom: 12 },
    route: ['osaka-hotel-start', 'usj'],
    stops: [
      {
        id: 'osaka-hotel-start',
        time: '约06:45',
        name: '大阪酒店出发',
        type: 'hotel',
        summary: '新今宫 → 西九条 → Universal City',
        detail: '大阪环状线换 JR 梦咲线，预计约30分钟；按当天开园时间倒推。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'usj',
        time: '全天',
        name: '日本环球影城',
        type: 'theme-park',
        summary: '开园前60–90分钟抵达',
        detail: '若任天堂世界是重点，提前处理门票、区域入场与 Express Pass；园区可能早于标示时间放行。',
        coordinates: [34.66544, 135.43234],
        officialUrl: 'https://www.usj.co.jp/web/ja/jp/park-guide/schedule/park-hour/',
        ticketUrl: 'https://www.usj.co.jp/ticket/',
      },
    ],
  },
  {
    id: 'd6',
    date: '10月9日',
    weekday: '周五',
    city: '大阪 → 香港',
    title: '大阪美食随逛 · 回程',
    eyebrow: '新世界 → 难波 → 关西机场',
    summary: '白天以美食和随意逛街为主，16:30前回酒店取行李，乘 UO863 返回香港。',
    status: { tone: 'warning', label: '17:30前往机场' },
    map: { center: [34.6652, 135.496], zoom: 13 },
    route: ['osaka-hotel-checkout', 'shinsekai', 'kuromon', 'dotonbori', 'shinsaibashi', 'osaka-hotel-pickup', 'kix-departure'],
    stops: [
      {
        id: 'osaka-hotel-checkout',
        time: '上午',
        name: '退房・寄存行李',
        type: 'hotel',
        summary: '轻装逛大阪市区',
        detail: '先向酒店确认当日寄存和最晚领取时间。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'shinsekai',
        time: '09:30',
        name: '新世界・通天阁',
        type: 'food',
        summary: '早餐、街区散步',
        detail: '就在酒店周边，保持轻松节奏。',
        coordinates: [34.6525, 135.5063],
        officialUrl: 'https://www.tsutenkaku.co.jp/Guide-pdf/mishiran-guide-english.pdf',
      },
      {
        id: 'kuromon',
        time: '11:30',
        name: '黑门市场・日本桥',
        type: 'food',
        summary: '小吃与随意逛街',
        detail: '不安排必须购买的清单，按现场食欲和人流决定。',
        coordinates: [34.6653, 135.50604],
        officialUrl: 'https://kuromon.com/en/',
      },
      {
        id: 'dotonbori',
        time: '13:30',
        name: '道顿堀・难波',
        type: 'food',
        summary: '午餐、甜品与街区漫游',
        detail: '控制排队时间，给最后取行李和机场交通留缓冲。',
        coordinates: [34.66872, 135.50129],
      },
      {
        id: 'shinsaibashi',
        time: '14:45',
        name: '心斋桥',
        type: 'shopping',
        summary: '自由逛街',
        detail: '16:00左右开始返回酒店。',
        coordinates: [34.6748, 135.50142],
      },
      {
        id: 'osaka-hotel-pickup',
        time: '16:30前',
        name: '返回酒店取行李',
        type: 'deadline',
        summary: '最迟17:30前往机场',
        detail: '从新今宫或难波选择当天最顺的机场线路。',
        coordinates: [34.65095, 135.5058],
      },
      {
        id: 'kix-departure',
        time: '18:00–18:30',
        name: '关西国际机场',
        type: 'airport',
        summary: '香港快运 UO863｜21:30起飞',
        detail: '预留国际航班值机、退税、安检与登机时间；10月10日00:40抵达香港。',
        coordinates: [34.43472, 135.24401],
        officialUrl: 'https://www.hkexpress.com/en-hk/',
      },
    ],
  },
];
